name: Update The Daily Tabloid

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours — you can change this
  workflow_dispatch:       # Lets you run it manually

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests   # Only requests is needed now

      - name: Generate site with GitHub AI
        run: python generate.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .            # Deploys index.html and articles folder
          force_orphan: true
